// Auto-generato da ElencoAtleti.xlsx
export const ELENCO_ATLETI = {
  'Affricano Linda': 'AQUARIUM VALLESCRIVIA',
  'Affricano Mattia': 'AQUARIUM VALLESCRIVIA',
  'Agazzi Emma': 'LAVAGNA 90',
  'Agosti Gilda': 'AQUARIUM VALLESCRIVIA',
  'Agosti Giovanni': 'AQUARIUM VALLESCRIVIA',
  'Alban Jimenez Noemi': 'AQUARIUM VALLESCRIVIA',
  'Alberti Gaia Juanita Olga': 'IDEA SPORT',
  'Alberti Sofie Olghita Vanessa': 'IDEA SPORT',
  'Albertini Daisy': 'NUOTATORI GENOVESI',
  'Alessandri Andrea': 'CROCERA STADIUM',
  'Alfieri Mattia': 'CROCERA STADIUM',
  'Allegri Simone': 'AQUARIUM VALLESCRIVIA',
  'Almasio Leon': 'RARI NANTES SPEZIA',
  'Alvarez Etiziana': 'LAVAGNA 90',
  'Amadi Fabio': 'RARI NANTES SPEZIA',
  'Amadi Giacomo': 'RARI NANTES SPEZIA',
  'Amadi Lorenzo': 'RARI NANTES SPEZIA',
  'Amato Emma': 'CROCERA STADIUM',
  'Ameri Ester': 'NUOTATORI GENOVESI',
  'Amerio Mattia': 'CROCERA STADIUM',
  'Anastasio Leonardo': 'CROCERA STADIUM',
  'Aresi Mario': 'IDEA SPORT',
  'Aresi Stefano': 'IDEA SPORT',
  'Armento Agnese': 'NUOTATORI GENOVESI',
  'Arnavas Enea': 'RARI NANTES SPEZIA',
  'Aste Viola': 'RAPALLO NUOTO',
  'Attardi Giacomo': 'SUPERBANUOTO',
  'Atzeni Paola': 'NUOTATORI GENOVESI',
  'Aurame Amelia': 'IDEA SPORT',
  'Avanzini Arianna': 'IDEA SPORT',
  'Badaracco Anna': 'RAPALLO NUOTO',
  'Badaracco Daniele': 'RAPALLO NUOTO',
  'Baiardi Giacomo': 'AQUARIUM',
  'Balducci Giulia': 'AQUARIUM VALLESCRIVIA',
  'Balzano Elvira': 'RARI NANTES SPEZIA',
  'Barale Alessandro': 'LAVAGNA 90',
  'Barbagelata Rebecca Matilda': 'NUOTATORI GENOVESI',
  'Barbetti Linda': 'RAPALLO NUOTO',
  'Baroni Sofia': 'NUOTATORI GENOVESI',
  'Barreca Melanie': 'IDEA SPORT',
  'Bellizzi Gaia': 'NUOTATORI GENOVESI',
  'Bellotti Agnese': 'NUOTATORI GENOVESI',
  'Bendazzoli Guglielmo': 'NUOTATORI GENOVESI',
  'Benini Filippo': 'RARI NANTES SPEZIA',
  'Bergamo Thomas': 'NUOTATORI GENOVESI',
  'Berra Celeste': 'IDEA SPORT',
  'Berruti Margherita': 'RAPALLO NUOTO',
  'Bertoletti Alessia': 'NUOTATORI GENOVESI',
  'Bestiaccia Bianca': 'RAPALLO NUOTO',
  'Bestoso Giovanni': 'NUOTATORI GENOVESI',
  'Bestoso Vittoria': 'NUOTATORI GENOVESI',
  'Bianchi Ludovica': 'AQUARIUM',
  'Bianchi Maya': 'AQUARIUM',
  'Bieler Henry': 'NUOTATORI GENOVESI',
  'Biggi Eleonora': 'NUOTATORI GENOVESI',
  'Biglietto Martina': 'CROCERA STADIUM',
  'Bisio Lorenzo': 'AQUARIUM',
  'Bistarini Filippo': 'NUOTATORI GENOVESI',
  'Boboc Pietro': 'RARI NANTES SPEZIA',
  'Boccato Asia': 'RARI NANTES SPEZIA',
  'Boero Riccardo': 'NUOTATORI GENOVESI',
  'Bonanni Francesca': 'RARI NANTES SPEZIA',
  'Bonati Luisotti Maia': 'RARI NANTES SPEZIA',
  'Bonino Umberto': 'NUOTATORI GENOVESI',
  'Borra Letizia': 'AQUARIUM',
  'Braini Martina': 'AQUARIUM VALLESCRIVIA',
  'Bravuzzo Nicolo\'': 'AQUARIUM VALLESCRIVIA',
  'Bregante Alberto': 'LAVAGNA 90',
  'Bregante Giulio': 'LAVAGNA 90',
  'Brianzi Jacopo': 'NUOTATORI GENOVESI',
  'Bucci Eleonora': 'IDEA SPORT',
  'Buttignon Maia': 'RAPALLO NUOTO',
  'Cabrera Condor Luis Carlos': 'NUOTATORI GENOVESI',
  'Cacciamani Ruben': 'IDEA SPORT',
  'Callo Sofie': 'RARI NANTES SPEZIA',
  'Camilli Mattia': 'IDEA SPORT',
  'Campilongo Antonella Lucia Emilia': 'CROCERA STADIUM',
  'Campisi Brigida': 'AQUARIUM',
  'Campodoni Matteo': 'RAPALLO NUOTO',
  'Canessa Federico': 'CROCERA STADIUM',
  'Cannata Matilde': 'AQUARIUM',
  'Canovaro Margherita': 'RAPALLO NUOTO',
  'Canovaro Mattia': 'NUOTATORI GENOVESI',
  'Caorsi Maita': 'NUOTATORI GENOVESI',
  'Caporello Chiara Maria Bernadette': 'LAVAGNA 90',
  'Caprili Cristian': 'IDEA SPORT',
  'Caprili Lorenzo': 'IDEA SPORT',
  'Capurro Giacomo': 'NUOTATORI GENOVESI',
  'Capurro Noah': 'RAPALLO NUOTO',
  'Carbonari Riccardo': 'RARI NANTES SPEZIA',
  'Carbonini Noah': 'LAVAGNA 90',
  'Carcheri Beatrice': 'IDEA SPORT',
  'Cartagenova Sara': 'NUOTATORI GENOVESI',
  'Castagneto Agata': 'RARI NANTES SPEZIA',
  'Castagnola Francesco': 'AQUARIUM VALLESCRIVIA',
  'Catalano Nicole': 'RARI NANTES SPEZIA',
  'Cataldi Lorenzo Luigi': 'NUOTATORI GENOVESI',
  'Cavallino Francesca': 'NUOTATORI GENOVESI',
  'Cecconi Alessia': 'LAVAGNA 90',
  'Cecconi Martina': 'LAVAGNA 90',
  'Celiberti Amelia': 'IDEA SPORT',
  'Celiberti Rachele': 'IDEA SPORT',
  'Celle Giada': 'LAVAGNA 90',
  'Celle Greta': 'LAVAGNA 90',
  'Celle Nicolas': 'LAVAGNA 90',
  'Cherubino Nicolo\'': 'NUOTATORI GENOVESI',
  'Chiesa Alessia': 'CROCERA STADIUM',
  'Chiesa Alice': 'RAPALLO NUOTO',
  'Chiesa Sofia': 'LAVAGNA 90',
  'Chiozza Clotilde': 'AQUARIUM VALLESCRIVIA',
  'Cirillo Riccardo': 'RARI NANTES SPEZIA',
  'Ciuffolotti Elia': 'NUOTATORI GENOVESI',
  'Coltrioli Matteo': 'NUOTATORI GENOVESI',
  'Colzani Federico': 'CROCERA STADIUM',
  'Conti Beatrice': 'NUOTATORI GENOVESI',
  'Coppa Fabio Giorgio': 'AQUARIUM',
  'Corbani Riccardo': 'RARI NANTES SPEZIA',
  'Corsanini Emma': 'RARI NANTES SPEZIA',
  'Corsiglia Marco': 'IDEA SPORT',
  'Costa Francesco': 'IDEA SPORT',
  'Costantini Riccardo': 'AQUARIUM VALLESCRIVIA',
  'Cristodero Martina': 'RARI NANTES SPEZIA',
  'Croce Daniele': 'CROCERA STADIUM',
  'Cuffini Emma': 'RARI NANTES SPEZIA',
  'Dado Vito Samuele': 'RARI NANTES SPEZIA',
  'Dagnino Bianca': 'CROCERA STADIUM',
  'Danioli Christian': 'LAVAGNA 90',
  'D\'Antonio Leonardo': 'AQUARIUM',
  'De Andreis Pietro': 'IDEA SPORT',
  'De Angelo Alessio': 'IDEA SPORT',
  'De Martino Lorenza': 'NUOTATORI GENOVESI',
  'Debenedetti Ludovica': 'AQUARIUM VALLESCRIVIA',
  'Della Queva Nicoletta': 'RARI NANTES SPEZIA',
  'Dellapina Alice': 'LAVAGNA 90',
  'Delucchi Chiara': 'NUOTATORI GENOVESI',
  'Demartini Viviana': 'LAVAGNA 90',
  'Devoto Giulia': 'NUOTATORI GENOVESI',
  'Di Donato Francesco': 'IDEA SPORT',
  'Donati Giulia': 'LAVAGNA 90',
  'Donizetti Diego': 'IDEA SPORT',
  'Dorcier Greta': 'CROCERA STADIUM',
  'Dorcier Pietro': 'CROCERA STADIUM',
  'D\'orsi Eleonora': 'NUOTATORI GENOVESI',
  'D\'orsi Emma': 'NUOTATORI GENOVESI',
  'Ercolani Nicola': 'SUPERBANUOTO',
  'Ercolano Beatrice': 'NUOTATORI GENOVESI',
  'Evola Ottavio': 'RARI NANTES SPEZIA',
  'Fabrizio Alessio': 'SUPERBANUOTO',
  'Favafabbri Alice': 'CROCERA STADIUM',
  'Fecondo Isabelle': 'RARI NANTES SPEZIA',
  'Ferrando Ludovica': 'NUOTATORI GENOVESI',
  'Ferrari Eleonora': 'AQUARIUM VALLESCRIVIA',
  'Ferrari Gian Marco': 'AQUARIUM VALLESCRIVIA',
  'Ferretti Francesco': 'AQUARIUM VALLESCRIVIA',
  'Filadelli Andrea': 'RARI NANTES SPEZIA',
  'Fiorillo Sofia': 'CROCERA STADIUM',
  'Florindi Anastasia': 'RARI NANTES SPEZIA',
  'Formentini Matteo': 'LAVAGNA 90',
  'Formentini Samuele': 'LAVAGNA 90',
  'Fossati Michele': 'AQUARIUM VALLESCRIVIA',
  'Fregosi Mattia': 'RARI NANTES SPEZIA',
  'Furloni Francesca': 'NUOTATORI GENOVESI',
  'Fuscagni Martina': 'NUOTATORI GENOVESI',
  'Gaggero Francesco': 'CROCERA STADIUM',
  'Galbusera Ginevra': 'NUOTATORI GENOVESI',
  'Gallesio Tommaso Sebastiano': 'RARI NANTES SPEZIA',
  'Gambaro Giulia': 'NUOTATORI GENOVESI',
  'Gambetta Agata': 'NUOTATORI GENOVESI',
  'Gammella Chiara': 'RARI NANTES SPEZIA',
  'Garassino Edoardo': 'IDEA SPORT',
  'Garassino Giorgia': 'IDEA SPORT',
  'Garbarino Luca': 'NUOTATORI GENOVESI',
  'Gelci Anna': 'IDEA SPORT',
  'Gentilino Alessia': 'RAPALLO NUOTO',
  'Gervasoni Giulia': 'IDEA SPORT',
  'Gessaga Luca': 'NUOTATORI GENOVESI',
  'Ghersi Elisa': 'NUOTATORI GENOVESI',
  'Ghettini Francesco': 'RARI NANTES SPEZIA',
  'Ghisolfo Stefano': 'RARI NANTES SPEZIA',
  'Gianelli Davide': 'RARI NANTES SPEZIA',
  'Giarrusso Martina': 'LAVAGNA 90',
  'Giordano Giorgia': 'RAPALLO NUOTO',
  'Giordano Lorenzo': 'IDEA SPORT',
  'Giordano Luca': 'RAPALLO NUOTO',
  'Giuffrida Emanuele': 'NUOTATORI GENOVESI',
  'Giuliani Giorgia': 'NUOTATORI GENOVESI',
  'Giuliano Matteo': 'CATEGORIA ESORDIENTI A2',
  'Giusti Martina': 'RARI NANTES SPEZIA',
  'Gnecco Ester': 'RAPALLO NUOTO',
  'Gnecco Gian Maria': 'LAVAGNA 90',
  'Gnecco Giorgia': 'RAPALLO NUOTO',
  'Gnecco Miriam': 'RAPALLO NUOTO',
  'Granda Cortez Giorgia Milena': 'NUOTATORI GENOVESI',
  'Grande Ludovica': 'LAVAGNA 90',
  'Grewing Lapo': 'IDEA SPORT',
  'Grillo Aurora': 'RARI NANTES SPEZIA',
  'Grondona Alice': 'AQUARIUM VALLESCRIVIA',
  'Gualco Giulia': 'AQUARIUM',
  'Guraschi Chiara': 'NUOTATORI GENOVESI',
  'Guskov Matvei': 'CROCERA STADIUM',
  'Iacono Isabella': 'RARI NANTES SPEZIA',
  'Iacono Pietro': 'RARI NANTES SPEZIA',
  'Iannone Giulia': 'NUOTATORI GENOVESI',
  'Imbesi Nicole': 'IDEA SPORT',
  'Incardona Matteo': 'IDEA SPORT',
  'Ionadi Filippo': 'RARI NANTES SPEZIA',
  'Kamberi Enton': 'RAPALLO NUOTO',
  'Kamberi Klea': 'RAPALLO NUOTO',
  'Kliken Gabriel': 'RAPALLO NUOTO',
  'Kravchuk Yana': 'IDEA SPORT',
  'La Corte Alessio': 'NUOTATORI GENOVESI',
  'Lagno Giada': 'RAPALLO NUOTO',
  'Lagorio Micole': 'LAVAGNA 90',
  'Lagorio Thomas': 'LAVAGNA 90',
  'Lamberti Leonardo': 'RARI NANTES SPEZIA',
  'Lanata Ginevra': 'RAPALLO NUOTO',
  'Lanini Veronica': 'NUOTATORI GENOVESI',
  'Lautanio Sofia': 'LAVAGNA 90',
  'Leveratto Elisa': 'NUOTATORI GENOVESI',
  'Levi Camilla': 'RARI NANTES SPEZIA',
  'Liguori Elisabetta': 'CROCERA STADIUM',
  'Lo Monaco Marta': 'NUOTATORI GENOVESI',
  'Lombardo Chiara': 'RARI NANTES SPEZIA',
  'Longo Gaia': 'RARI NANTES SPEZIA',
  'Longo Jacopo': 'RARI NANTES SPEZIA',
  'Losciale Alice': 'CROCERA STADIUM',
  'Lucchin Miriam May': 'RARI NANTES SPEZIA',
  'Luciardi Gabriele': 'NUOTATORI GENOVESI',
  'Luciardi Lorenzo': 'NUOTATORI GENOVESI',
  'Lucido Pietro': 'NUOTATORI GENOVESI',
  'Macaj Riccardo': 'CROCERA STADIUM',
  'Maccari Elisa': 'NUOTATORI GENOVESI',
  'Macchiavello Pietro': 'LAVAGNA 90',
  'Machieraldo Leonardo': 'IDEA SPORT',
  'Magliulo Simone': 'NUOTATORI GENOVESI',
  'Malaspina Elena': 'AQUARIUM',
  'Malatesta Beatrice': 'NUOTATORI GENOVESI',
  'Maloni Elisa': 'RARI NANTES SPEZIA',
  'Malpezzi Alessandro': 'CROCERA STADIUM',
  'Malpezzi Beatrice': 'CROCERA STADIUM',
  'Manarola Nadir': 'IDEA SPORT',
  'Mandelli Ilaria': 'RAPALLO NUOTO',
  'Mangiante Camilla': 'LAVAGNA 90',
  'Mantovani Alex': 'AQUARIUM',
  'Mantovani Edoardo': 'NUOTATORI GENOVESI',
  'Mantovani Irene': 'NUOTATORI GENOVESI',
  'Marchelli Filippo': 'AQUARIUM',
  'Marenco Martina': 'AQUARIUM',
  'Martini Federica': 'RAPALLO NUOTO',
  'Martini Sofia': 'RAPALLO NUOTO',
  'Marzolla Lavinia': 'LAVAGNA 90',
  'Massari Nicholas': 'LAVAGNA 90',
  'Massone Anna': 'AQUARIUM',
  'Massone Sofia': 'NUOTATORI GENOVESI',
  'Massucco Anita': 'LAVAGNA 90',
  'Massucco Federico': 'NUOTATORI GENOVESI',
  'Massucco Giulia': 'NUOTATORI GENOVESI',
  'Mastellaro Carola': 'AQUARIUM',
  'Mazza Alexej': 'CROCERA STADIUM',
  'Mazzeo Anna': 'AQUARIUM',
  'Mellina Bares Matteo': 'NUOTATORI GENOVESI',
  'Meneghetti Anna': 'IDEA SPORT',
  'Meneghetti Luca': 'IDEA SPORT',
  'Meneghetti Marianna': 'NUOTATORI GENOVESI',
  'Menini Lorenzo': 'RARI NANTES SPEZIA',
  'Menoni Maria Vittoria': 'RARI NANTES SPEZIA',
  'Merighi Giuseppe': 'LAVAGNA 90',
  'Merlano Giacomo Mattia': 'AQUARIUM',
  'Mihai Petrescu Daniel': 'LAVAGNA 90',
  'Milan Filippo': 'LAVAGNA 90',
  'Minnai Federico Francesco': 'NUOTATORI GENOVESI',
  'Moirano Martina': 'IDEA SPORT',
  'Molin Anne Camille': 'NUOTATORI GENOVESI',
  'Molinar Min Rachele': 'IDEA SPORT',
  'Molinari Martin Alberto': 'NUOTATORI GENOVESI',
  'Molinari martin Alberto': 'NUOTATORI GENOVESI',
  'Molle Caterina': 'IDEA SPORT',
  'Molle Pietro': 'IDEA SPORT',
  'Monachesi Stella': 'RAPALLO NUOTO',
  'Monaco Sofia': 'RARI NANTES SPEZIA',
  'Monari Sara': 'NUOTATORI GENOVESI',
  'Montanari Pietro': 'RARI NANTES SPEZIA',
  'Monte Lavinia': 'RAPALLO NUOTO',
  'Monte Margherita': 'RAPALLO NUOTO',
  'Morano Nicola': 'NUOTATORI GENOVESI',
  'Moretti Athena': 'NUOTATORI GENOVESI',
  'Moretto Alessio': 'CROCERA STADIUM',
  'Moscatelli Alessandro': 'NUOTATORI GENOVESI',
  'Moscatelli Francesco': 'NUOTATORI GENOVESI',
  'Nadalin Achille': 'RAPALLO NUOTO',
  'Naselli Ester Elsa': 'CROCERA STADIUM',
  'Naselli Luca': 'RAPALLO NUOTO',
  'Negrello Tommaso': 'NUOTATORI GENOVESI',
  'Neri Pierpaolo': 'RARI NANTES SPEZIA',
  'Nicoletta Beatrice': 'AQUARIUM VALLESCRIVIA',
  'Nigra Edoardo': 'IDEA SPORT',
  'Nucera Lara': 'CROCERA STADIUM',
  'Odaglia Carlotta': 'RAPALLO NUOTO',
  'Orlando Filippo': 'RARI NANTES SPEZIA',
  'Orlando Lara': 'RARI NANTES SPEZIA',
  'Osimani Davide': 'LAVAGNA 90',
  'Ottonello Ambra': 'IDEA SPORT',
  'Paita Sofia': 'RARI NANTES SPEZIA',
  'Palumbo Anna': 'CATEGORIA ESORDIENTI A2',
  'Pannacciulli Elena': 'NUOTATORI GENOVESI',
  'Papini Adele': 'RARI NANTES SPEZIA',
  'Parodi Alessio': 'CROCERA STADIUM',
  'Parolisi Rebecca': 'AQUARIUM',
  'Parolo Vittoria': 'IDEA SPORT',
  'Passera Alex': 'RAPALLO NUOTO',
  'Pastrovicchio Luca': 'NUOTATORI GENOVESI',
  'Pastrovicchio Marco': 'NUOTATORI GENOVESI',
  'Pastrovicchio Sara': 'NUOTATORI GENOVESI',
  'Pelizza Adele': 'AQUARIUM VALLESCRIVIA',
  'Pelizza Emma': 'AQUARIUM',
  'Pellegri Caterina': 'NUOTATORI GENOVESI',
  'Pellegrinelli Leonardo': 'RARI NANTES SPEZIA',
  'Perasso Emanuele': 'AQUARIUM VALLESCRIVIA',
  'Peron Alessia': 'AQUARIUM',
  'Perrone Bianca': 'NUOTATORI GENOVESI',
  'Perrone Olivia': 'NUOTATORI GENOVESI',
  'Persano Filippo': 'AQUARIUM',
  'Pessagno Ludovica': 'LAVAGNA 90',
  'Piccardo Filippo': 'NUOTATORI GENOVESI',
  'Picerno Camilla': 'LAVAGNA 90',
  'Pinasco Agnese Rosa': 'LAVAGNA 90',
  'Pirre\' Alessandro': 'NUOTATORI GENOVESI',
  'Pirrotta Davide Marco Amos': 'IDEA SPORT',
  'Pirrotta Sara Elisa Silvia': 'IDEA SPORT',
  'Pisanelli Yndestad Martin': 'RARI NANTES SPEZIA',
  'Poggiali Gioia': 'NUOTATORI GENOVESI',
  'Pontanari Joel': 'IDEA SPORT',
  'Ponti Vittoria': 'CATEGORIA ESORDIENTI A2',
  'Popovici Erika': 'RARI NANTES SPEZIA',
  'Popovici Erika Maria': 'RARI NANTES SPEZIA',
  'Pordenon Erica': 'AQUARIUM VALLESCRIVIA',
  'Pordenon Mirco': 'AQUARIUM VALLESCRIVIA',
  'Porta Amalia': 'AQUARIUM',
  'Porta Lorenzo': 'IDEA SPORT',
  'Prado Aray Aurora': 'IDEA SPORT',
  'Prato Riccardo': 'NUOTATORI GENOVESI',
  'Profumo Luca': 'CROCERA STADIUM',
  'Quagliaroli Mariana Elisabeth': 'NUOTATORI GENOVESI',
  'Rabagliati Ilaria': 'NUOTATORI GENOVESI',
  'Rama Caterina': 'LAVAGNA 90',
  'Ramazzotto Maribel': 'LAVAGNA 90',
  'Razzetti Enrico': 'LAVAGNA 90',
  'Remondino Ginevra': 'IDEA SPORT',
  'Repetto Filippo': 'AQUARIUM',
  'Repetto Lisa': 'AQUARIUM VALLESCRIVIA',
  'Repetto Stella': 'NUOTATORI GENOVESI',
  'Reppetti Sofia': 'AQUARIUM',
  'Riccardi Filippo': 'IDEA SPORT',
  'Riccardi Matilde': 'IDEA SPORT',
  'Ricciardi Manuel': 'RARI NANTES SPEZIA',
  'Ricciardi Niccolo\'': 'RARI NANTES SPEZIA',
  'Risso Agata': 'IDEA SPORT',
  'Risso Lucia': 'RAPALLO NUOTO',
  'Rivellini Giada': 'NUOTATORI GENOVESI',
  'Roccato Ginevra': 'NUOTATORI GENOVESI',
  'Rollandi Giulia': 'LAVAGNA 90',
  'Romanini Giorgia': 'AQUARIUM',
  'Romitelli Giulia Angela': 'NUOTATORI GENOVESI',
  'Roncoli Alessandro': 'AQUARIUM',
  'Rossetti Sofia': 'NUOTATORI GENOVESI',
  'Rossi Alberto': 'SUPERBANUOTO',
  'Rossi Francesco': 'IDEA SPORT',
  'Rossi Giorgia': 'RARI NANTES SPEZIA',
  'Rossi Matteo': 'NUOTATORI GENOVESI',
  'Rota Alessio': 'NUOTATORI GENOVESI',
  'Rovere Filippo': 'IDEA SPORT',
  'Rovere Giacomo': 'IDEA SPORT',
  'Ruggiero Pierpaolo': 'SUPERBANUOTO',
  'Salvaneschi Anna Giulia': 'AQUARIUM',
  'Samandi Hassen': 'RAPALLO NUOTO',
  'Sanfratello Luca': 'IDEA SPORT',
  'Sanna Aurora': 'LAVAGNA 90',
  'Santagostino Vittoria': 'RARI NANTES SPEZIA',
  'Sara\' Laura': 'NUOTATORI GENOVESI',
  'Saraniti Lana Tommaso': 'RARI NANTES SPEZIA',
  'Sarbia Melissa': 'RARI NANTES SPEZIA',
  'Savio Giulia': 'NUOTATORI GENOVESI',
  'Savio Pietro': 'NUOTATORI GENOVESI',
  'Scaffaro Roberto': 'CROCERA STADIUM',
  'Scaramel Simone': 'AQUARIUM VALLESCRIVIA',
  'Scarongella Gaia': 'CROCERA STADIUM',
  'Schiavoni Stefano': 'AQUARIUM',
  'Scianda Greta': 'IDEA SPORT',
  'Scianda Mirko': 'IDEA SPORT',
  'Sclavo Ginevra': 'IDEA SPORT',
  'Scotti Lorenzo': 'RAPALLO NUOTO',
  'Scotti Samuel': 'CROCERA STADIUM',
  'Sechi Francesco': 'CROCERA STADIUM',
  'Senes Roberto Tommaso': 'NUOTATORI GENOVESI',
  'Serio Edoardo': 'CROCERA STADIUM',
  'Sesca Anna': 'IDEA SPORT',
  'Signini Thomas': 'NUOTATORI GENOVESI',
  'Sodero Leonardo': 'RARI NANTES SPEZIA',
  'Solari Valentina': 'CROCERA STADIUM',
  'Spartani Lorenzo': 'RAPALLO NUOTO',
  'Strasia Mattia': 'NUOTATORI GENOVESI',
  'Tancredi Alessandro': 'AQUARIUM',
  'Tancredi Valentina': 'AQUARIUM',
  'Tassara Marta': 'NUOTATORI GENOVESI',
  'Test Test': 'CATEGORIA ESORDIENTI A2',
  'Tizzoni Giorgia': 'NUOTATORI GENOVESI',
  'Tonelli Alessio': 'RARI NANTES SPEZIA',
  'Tonelli Diego': 'RARI NANTES SPEZIA',
  'Torre Lorenzo': 'RARI NANTES SPEZIA',
  'Toscani Chiara': 'CROCERA STADIUM',
  'Trianni Rossana': 'CROCERA STADIUM',
  'Tricarico Adriano': 'CROCERA STADIUM',
  'Trocchia Ettore': 'RARI NANTES SPEZIA',
  'Trocchia Jole': 'RARI NANTES SPEZIA',
  'Trovo\' Lucia': 'RAPALLO NUOTO',
  'Uccelli Virginia': 'IDEA SPORT',
  'Vaccaro Tommaso': 'RARI NANTES SPEZIA',
  'Vagge Mauro': 'NUOTATORI GENOVESI',
  'Valente Samuele': 'RAPALLO NUOTO',
  'Valle Valentina': 'IDEA SPORT',
  'Vallebuona Umberto': 'RAPALLO NUOTO',
  'Valperga Davide': 'LAVAGNA 90',
  'Venuti Alberto': 'CROCERA STADIUM',
  'Vernaleone Beatrice': 'IDEA SPORT',
  'Vernaleone Daniele': 'IDEA SPORT',
  'Vicini Andrea': 'LAVAGNA 90',
  'Vignolo Tyra': 'RAPALLO NUOTO',
  'Villa Adelina': 'NUOTATORI GENOVESI',
  'Vio Camilla': 'IDEA SPORT',
  'Viola Vittoria': 'NUOTATORI GENOVESI',
  'Xhepnuzi Elisa': 'RARI NANTES SPEZIA',
  'Zaccagno Giorgia': 'RARI NANTES SPEZIA',
  'Zaccagno Samuele': 'RARI NANTES SPEZIA',
  'Zago Beatrice': 'IDEA SPORT',
  'Zanco Christian': 'SUPERBANUOTO',
  'Zannini Ilaria': 'NUOTATORI GENOVESI',
  'Zannoni Chiara': 'SUPERBANUOTO',
  'ZANONI SARA': 'RAPALLO NUOTO',
  'Zeppetella Silvana': 'RARI NANTES SPEZIA',
  'Zola Emilio Francesco': 'RARI NANTES SPEZIA',
  'Zola Leonardo': 'RARI NANTES SPEZIA',
}